export const TEST_ACTION = 'TEST_ACTION';
export const TEST_ACTION_HANDLED = 'TEST_ACTION_HANDLED';

// ---- Users ------
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE';

export const FETCH_ALL_PERSONNEL = 'FETCH_ALL_PERSONNEL';
export const FETCH_ALL_PERSONNEL_SUCCESS = 'FETCH_ALL_PERSONNEL_SUCCESS';
export const FETCH_ALL_PERSONNEL_FAILURE = 'FETCH_ALL_PERSONNEL_FAILURE';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const CHANGE_ROLE = 'CHANGE_USER_ROLE';
export const CHANGE_ROLE_SUCCESS = 'CHANGE_USER_ROLE_SUCCESS';
export const CHANGE_ROLE_FAILURE = 'CHANGE_USER_ROLE_FAILURE';

//  ---- Projects -----
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';


//  ----- Common ------
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
